return {
    fps = 24,
    rigs = {
        ["Rig2"] = {
            [1] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [4] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [6] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [10] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [14] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
        },
        ["Rig1"] = {
            [1] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [12] = {
                ["Left Leg"] = {1, 14.2754, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [14] = {
                ["Left Leg"] = {1, 14.2754, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [16] = {
                ["Left Leg"] = {1, 23.7708, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
        },
    },
}