return {
    fps = 24,
    rigs = {
        ["Stuntman"] = {
            [1] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [2] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [3] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [4] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [5] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [6] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [7] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [8] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [9] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [10] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [11] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [12] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [13] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [14] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [15] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [16] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [17] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [18] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [19] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [20] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [21] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [22] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [23] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [24] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [25] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [26] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [27] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [28] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [29] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [30] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [31] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [32] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [33] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [34] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [35] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [36] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [37] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [38] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [39] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [40] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [41] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [42] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [43] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [44] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [45] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
        },
    },
    easings = {
        ["Stuntman"] = {
        },
    },
}