return {
    fps = 1,
    rigs = {
        ["Stuntman"] = {
            [1] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [2] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [3] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [4] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [5] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [6] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [7] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [8] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [9] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [10] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [11] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [12] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [13] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [14] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [15] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [16] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [17] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [18] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [19] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [20] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [21] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [22] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [23] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [24] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [25] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [26] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [27] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [28] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [29] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
            [30] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Right Leg"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Left Arm"] = {1, 2, 1},
            },
        },
    },
    easings = {
        ["Stuntman"] = {
            [14] = "EaseOut",
            [15] = "EaseOut",
            [16] = "EaseOut",
            [17] = "EaseOut",
            [18] = "EaseOut",
            [19] = "EaseOut",
            [20] = "EaseOut",
            [21] = "EaseOut",
            [22] = "EaseOut",
            [23] = "EaseOut",
            [24] = "EaseOut",
            [25] = "EaseOut",
            [26] = "EaseOut",
            [27] = "EaseOut",
            [28] = "EaseOut",
            [29] = "EaseOut",
            [30] = "EaseOut",
        },
    },
}