return {
    fps = 10,
    rigs = {
        ["RigGiver"] = {
            [1] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [2] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [3] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [4] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [5] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [6] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [7] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [8] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [9] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [10] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [11] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [12] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [13] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [14] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [15] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [16] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
        },
        ["RigReceiver"] = {
            [1] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [2] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [3] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [4] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [5] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [6] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [7] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [8] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [9] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [10] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [11] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [12] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [13] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [14] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [15] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
            [16] = {
                ["Left Leg"] = {1, 2, 1},
                ["Right Arm"] = {1, 2, 1},
                ["Head"] = {2, 1, 1},
                ["Left Arm"] = {1, 2, 1},
                ["Torso"] = {2, 2, 1},
                ["HumanoidRootPart"] = {2, 2, 1},
                ["Right Leg"] = {1, 2, 1},
            },
        },
    },
    easings = {
        ["RigGiver"] = {
            [8] = "EaseOut",
        },
        ["RigReceiver"] = {
            [8] = "EaseOut",
        },
    },
}